### ISSUE TITLE
The problem about ' optimizing minimum filter number exception in dataname'

### ISSUE THREAD

**Issue by tqwang743** [maiziezhoulab/ADEPT#1]
Hi,

It is a fantastic method for analyzing spatial transcriptomics!

When I run the code `python ADEPT_main.py --input_data=../151673 --cluster_num=7 --radius=150 --use_hvgs=0 --runs=3 --de_candidates=150,200,250,300,350,400 --impute_runs=1`, I encountered the problem shown below. 
![image](https://github.com/maiziezhoulab/ADEPT/assets/108932740/1f635f3d-eb46-428b-83f6-49dd7f556312)

I don't know how to do it. Can you give me some advice？Thank you very much!

**Comment by OliiverHu** [comment]
Hi! Thanks for having interest in our work! I see you have already closed the issue on your end. Is there anything that I can do to help?

**Comment by tqwang743** [comment]
Thank you for your reply. I have solved the problem so I closed the issue.

**Comment by OliiverHu** [comment]
Great! Good luck with your research. LMK if you have any further questions.
