### ISSUE TITLE
Questions about the 'layer' information of STARmap dataset

### ISSUE THREAD

**Issue by wan-nie** [maiziezhoulab/ADEPT#2]
Hi Yunfei,

Thank you for your thorough and impressive study. In the original repository of [STARmap](https://www.dropbox.com/sh/f7ebheru1lbz91s/AACIAqjvDv--mhnE-PmSXB41a/visual_1020?dl=0&subfolder_nav_tracking=1), from my understanding, the repository only provides cell-type labels for the cells, rather than 'layer' labels.

Before reading your paper, I noticed that SpaGCN also analyzed the STARmap dataset. However, I couldn't find the STARmap dataset uploaded on their [GitHub](https://github.com/jianhuupenn/SpaGCN) repository. I have been searching for the 'layer' labels for some time, and I recently came across ADEPT. I noticed that you cited SpaGCN as the source for the STARmap dataset. Could you please share how you obtained the 'label' information from SpaGCN? I would greatly appreciate any insights you can provide.

Thank you

**Comment by OliiverHu** [comment]
Hi! 

Thanks for your interest in our project. Hope you have already figured it out. 

If not I will send you a copy of the data we are using.

regards

**Comment by OliiverHu** [comment]
Hi!

Hope you have this issue figured out. I think the layer labels are just stored in the fourth column of the data.obs. LMK if there are actually other concerns.

Regards,
